### PR TITLE
Replaced HarmonyPatch strings with nameof

### PR DESCRIPTION
**Pull request by MSchmoecker**
This changes nothing for the current version but allows to easier spot if something is broken. As H&H is around the corner and will probably brake a lot, this could save some time

Edit: Sneaked a change in so the version has only to be changed in one place :P

### CODE REVIEW

**Comment by jhedin** [comment]
Is there a way for handling all of these nameofs being private in the dlls?

**Comment by MSchmoecker** [comment]
Do you mean the patch functions are private or something else? `nameof` is evaluated at compile time and not visible in the resulting dll.

Nevertheless, the mod is broken for the current Valheim version and I (and probably ontrigger, too) don't plan to revive the mod in the near future. Most of the important optimizations are already implemented in the base game and the remaining features here are very experimental and hard to maintain in my opinion. But the mod is MIT licensed, feel free to fork and fix it if you want to.

**Comment by MSchmoecker** [comment]
Oh, on second reading I know what you mean. You need publicized Valheim dlls present at `VALHEIM_INSTALL\valheim_Data\Managed\publicized_assemblies\assembly_[assembly]_publicized.dll`. Use any publicizer, for example: https://github.com/CabbageCrow/AssemblyPublicizer

**Comment by jhedin** [comment]
Did the trick, thanks!

I'm really looking to make the mists run better, with a first guess on adding an object pool to the mist makers, thus reusing this code.


.... So far reading the decompilations, I'm not convinced misters ever go away, so that might solve my "eventually the game slows down to 5fps" problem

**Pull request merged**
