### PR TITLE
fixed lag spikes caused by heightmap Mesh.Bake CollisionData

### PR DESCRIPTION
**Pull request by MSchmoecker**
This improves big lag spikes caused by Heightmap `Regenerate` in the main thread. The whole Mesh generation could be improved further, here only `Mesh.Bake` is moved to a separate thread.

This change basically stores the current mesh, let it bake in a second thread and then assign it to the MeshCollider in Update. I am using a Transpiler because I don't want to copy the whole function just to change one line.

### CODE REVIEW

**Comment by ontrigger** [comment]
Oh, I was actually just working on that, damn

**Comment by MSchmoecker** [comment]
Oh, that is unfortunate, I have only seen you have been working  on object pooling. 

I am currently not sure about `Thread.Sleep(0)` as it causes some continues CPU usage. On my hardware it is not a problem but maybe on a lower ended one. Unity's main thread should be able to gain priority or at least the same treatment so this may be not a problem (but I can't really test it).
Maybe we should call `Thread.Sleep(1)` or `Thread.Sleep(1)` only when `next == null` and the loop waits anyway. This way it could fast process lots of data and don't consume much idle CPU.

**Comment by ontrigger** [comment]
Would it perhaps be better to use signaling instead?
http://www.albahari.com/threading/part2.aspx#_Signaling_with_Event_Wait_Handles

**Comment by MSchmoecker** [comment]
Yes I like the signal. Now there is no need to check if the queue contains elements because there will always be one.

**Comment by ontrigger** [comment]
The patch seems to break worldgen, any ideas?
image

**Comment by ontrigger** [comment]
Oh boy, it looks like the game needs the collision mesh as soon as the heightmap is instantiated because all the props are placed by raycasting. My efforts didn't work out either 😕

**Comment by MSchmoecker** [comment]
In ClutterSystem is the method IsHeightmapReady which can easily be adjusted to work with the new system. Other calls like WearNTear Update might not be necessary to adjust because the timing should be no problem, although this has to be tested further.
Your screenshot is from generating a new world, right?

**Comment by ontrigger** [comment]
The screenshot is from a generated world, I'm just flying into new, unsaved chunks.
The ClutterSystem class is for grass, the actual prop placement is done in ZoneSystem.PlaceVegetation.

**Comment by MSchmoecker** [comment]
Now the ZoneSystem spawns the heightmap but doesn't place any locations or vegetation. This applies only to new generated chunks, old ones are still broken of course. 
As the build queue was pushing more elements then it processed, I removed the waithandler.

**Comment by ontrigger** [comment]
Do you have discord? It's a bit difficult tying to communicate through pull request comments `ontrigger#7187`

**Pull request merged**
